### ISSUE TITLE
Client-side js minificated bundle

### ISSUE THREAD

**Issue by artemtam** [vpotseluyko/school30#9]
App must build one minificated js file for production

**Comment by vpotseluyko** [comment]
https://www.npmjs.com/package/express-asset-manager
smth like that shall go

**Comment by vpotseluyko** [comment]
Implemented webpack frontend bundling
commits -
f57905163490eacea1a8fc958e1918a2193f5528 
3f3a6ef10c84f47af918556fd9bde741b30c370f
